changes on UserDTOMapper and User Entity
sopra-fs21-group-02/server pull request #102
Opened 2021-04-09 12:04 UTC by celine-s

Resolves #75

2021-04-09 20:06 UTC, KseniaBel commented
@celine-s the code build fails

2021-04-09 20:18 UTC, KseniaBel commented on src/main/java/ch/uzh/ifi/hase/soprafs21/entity/Tag.java
> +@Table(name = "DOGS", schema="soprafs21")
DOGS?

2021-04-10 13:46 UTC, bschne requested changes

2021-04-10 13:46 UTC, bschne commented on src/main/java/ch/uzh/ifi/hase/soprafs21/rest/mapper/UserDTOMapper.java
> +    //@Mapping(source = "latestLocation", target = "latestLocation")
If we need this property (I think we do), we should add it to the entities & map it here. If we don't need it, we should remove it entirely.

2021-04-10 13:46 UTC, bschne commented on src/main/java/ch/uzh/ifi/hase/soprafs21/rest/mapper/UserDTOMapper.java
> +    //@Mapping(source = "latestLocation", target = "latestLocation")
See above.

2021-04-11 18:29 UTC, KseniaBel commented on src/main/java/ch/uzh/ifi/hase/soprafs21/entity/User.java
I think we do not need to have conversations in UserDTO since we get all the conversation of user in a separate call. I do not remember the reason why I included it in API, but I will remove it.

2021-04-12 13:22 UTC, celine-s commented on src/main/java/ch/uzh/ifi/hase/soprafs21/entity/User.java
👍 I removed it in the entity as well.

2021-04-12 14:31 UTC, nehasingh1491 approved these changes
looks good

2021-04-12 14:36 UTC, bschne approved these changes

2021-04-12 14:37 UTC, merged